spec:
  - tests/basic-read-write.test.js
  - tests/directory.test.js
  - tests/acl.test.js
  - tests/cas.test.js
  - tests/partitions.test.js
  - tests/ld-operations.test.js
  - tests/transfer.test.js
  - tests/http-fs.test.js
  - tests/cli.test.js
timeout: 30000
require: tests/helpers/env.js
